catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.book_detail_view, name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.AllBorrowedBooks.as_view(), name='borrowed_books'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian,
         name='renew-book-librarian'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('author/<int:pk>/update/',
         views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/',
         views.AuthorDelete.as_view(), name='author-delete'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
# Used to generate URLs by reversing the URL patterns
import uuid  # Required for unique book instances
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from datetime import date


# Create your models here.


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author is a string rather than an object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(
        max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(
        Genre, help_text='Select a genre for this book')

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

catalog/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views import generic
import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from catalog.forms import RenewBookForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


# Create your views here.
from .models import Book, Author, BookInstance, Genre


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(
        status__exact='a').count()

    # The 'all()' is implied by default.
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()
    particular_book = Book.objects.filter(title__icontains='w').count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'particular_book': particular_book,
        'num_genres': num_genres,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    template_name = 'catalog/book_form.html'


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    template_name = 'catalog/book_update_form.html'


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')


class AuthorCreate(CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/06/2020'}


class AuthorUpdate(UpdateView):
    model = Author
    # Not recommended (potential security issue if more fields added)
    fields = '__all__'


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


class BookListView(generic.ListView):
    model = Book
    template_name = 'book_list.html'
    paginate_by = 10


class AuthorListView(generic.ListView):
    model = Author
    template_name = 'author_list.html'
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author_detail.html'


def book_list(request):
    book_list = Book.objects.all()
    context = {
        'book_list': book_list
    }
    return render(request, 'book_list.html', context=context)


def book_detail_view(request, pk):
    book = get_object_or_404(Book, pk=pk)
    return render(request, 'book_detail.html', context={'book': book})


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )


class AllBorrowedBooks (PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/borrowed_books.html'
    paginate_by = 10

    def get_queryset(self):
        return (BookInstance.objects.filter(status__exact='o')).order_by('due_back')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('borrowed_books'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

catalog/templates/author_detail.html
{% extends "base_generic.html" %} {% block content %}
<h1>Title: {{ author.first_name }} {{ author.last_name }}</h1>

<!-- author detail link not yet defined -->
<p>
	<strong>Date of Death: </strong> {% if author.date_of_death %} 
    {{ author.date_of_death }} {% else %} Still Alive {% endif %}
</p>
<p>
	<strong>Date of birth: </strong>{% if author.birth %} {{ author.birth }} 
    {% else %} Not Set {% endif %}
</p>
<p>
    {% if user.is_staff  %}

<a href="{% url 'author-delete' author.id %}" class="btn btn-danger">Delete Author</a>
{% endif %}
</p>
{% endblock %}

catalog/templates/author_list.html
{% extends "base_generic.html" %} {% block content %}
<h1>Author List</h1>
{% if author_list %}
<ul>
	{% for author in author_list %}
	<li>
		<a href="{{ author.get_absolute_url }}"
			>{{ author.first_name }} {{ author.last_name }}</a
		>
	</li>
	<li><strong>Date of birth: </strong>{% if author.birth %} 
        {{ author.birth }} {% else %} Not Set {% endif %}</li>
	<li>
		<strong>Date of Death: </strong>{% if author.date_of_death %} 
        {{ author.date_of_death }} {% else %} Still Alive {% endif %}
	</li>
	{% endfor %}
</ul>
{% else %}
<p>There are no authors.</p>



{% endif %} 

{% if user.is_staff  %}

<a href="{% url 'author-create' %}" class="btn btn-primary">Add Author</a>
{% endif %}
{% endblock %}

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% block title %}
		<title>Local Library</title>
		{% endblock %}
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
			crossorigin="anonymous"
		/>
		<!-- Add additional CSS in static file -->
		{% load static %}
		<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-2">
					{% block sidebar %}
					<ul class="sidebar-nav">
						<li><a href="{% url 'index' %}">Home</a></li>
						<li><a href="{% url 'books' %}">All books</a></li>
						<li><a href="{% url 'authors' %}">All authors</a></li>
					</ul>
					<ul class="sidebar-nav">
						{% if user.is_authenticated %}
						<li>User: {{ user.get_username }}</li>
						<li><li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li></li>
						<li>
							<a href="{% url 'logout' %}?next={{ request.path }}">Logout</a>
						</li>
						{% else %}
						<li>
							<a href="{% url 'login' %}?next={{ request.path }}">Login</a>
						</li>
						{% endif %}
					</ul>
					<ul class="sidebar-nav">
						{% if user.is_staff  %}
						<li>Staff : </li>
						<li><a href="{% url 'borrowed_books' %}">All Borrowed</a></li>
						{% endif %}
					</ul>

					{% endblock %}
				</div>
				<div class="col-sm-10">
					{% block content %}{% endblock %} {% block pagination %} 
					{% if is_paginated %}
					<div class="pagination">
						<span class="page-links">
							{% if page_obj.has_previous %}
							<a
								href="{{ request.path }}?page={{ page_obj.previous_page_number }}"
								>previous</a
							>
							{% endif %}
							<span class="page-current">
								Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
							</span>
							{% if page_obj.has_next %}
							<a href="{{ request.path }}?page={{ page_obj.next_page_number }}"
								>next</a
							>
							{% endif %}
						</span>
					</div>
					{% endif %} {% endblock %}
				</div>
			</div>
		</div>
	</body>
</html>

catalog/templates/book_detail.html
{% extends "base_generic.html" %} {% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="">{{ book.author }}</a></p>
<!-- author detail link not yet defined -->
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p>
<p><strong>Language:</strong> {{ book.language }}</p>
<p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

<div style="margin-left: 20px; margin-top: 20px">
	<h4>Copies</h4>

	{% for copy in book.bookinstance_set.all %}
	<hr />
	<p
		class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}"
	>
		{{ copy.get_status_display }}
	</p>
	{% if copy.status != 'a' %}
	<p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
	{% endif %}
	<p><strong>Imprint:</strong> {{ copy.imprint }}</p>
	<p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
	{% endfor %}
</div>

{% if user.is_staff  %}

<a href="{% url 'book-update' book.id %}" class="btn btn-primary">Update Book</a>
{% endif %}
{% endblock %}

catalog/templates/book_list.html
{% extends "base_generic.html" %} {% block content %}
<h1>Book List</h1>
{% if book_list %}
<ul>
	{% for book in book_list %}
	<li class="m-2">
		<a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
		({{book.author}}) {% if user.is_staff  %}

<a href="{% url 'book-delete' book.id %}" class="btn btn-danger">Delete Book</a>
{% endif %}
	</li>
	{% endfor %}
</ul>
{% else %}
<p>There are no books in the library.</p>
{% endif %} 

{% if user.is_staff  %}

<a href="{% url 'book-create' %}" class="btn btn-primary">Add Book</a>
{% endif %}

{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %} {% block content %}
<h1>Local Library Home</h1>
<p>
	Welcome to LocalLibrary, a website developed by
	<em>Mozilla Developer Network</em>!
</p>
<h2>Dynamic content</h2>
<p>The library has the following record counts:</p>
<ul>
	<li><strong>Books:</strong> {{ num_books }}</li>
	<li><strong>Copies:</strong> {{ num_instances }}</li>
	<li><strong>Copies available:</strong> {{ num_instances_available }}</li>
	<li><strong>Authors:</strong> {{ num_authors }}</li>
	<li><strong>Genres:</strong>{{ num_genres }}</li>
	<li><strong>Books W:</strong>{{ particular_book }}</li>
</ul>
<p>
	You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.
</p>
{% endblock %}